[build]
  command = "npm run build"
  publish = "dist"

# Replace BACKEND_ORIGIN with your deployed Node server URL
# Example: https://attendance-backend.onrender.com

[[redirects]]
  from = "/api/*"
  to = "https://BACKEND_ORIGIN/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://BACKEND_ORIGIN/socket.io/:splat"
  status = 200
  force = true
  headers = { Connection = "upgrade" }


