[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_BACKEND_HOST/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://YOUR_BACKEND_HOST/socket.io/:splat"
  status = 200
  force = true
  headers = { Connection = "upgrade" }
